### PR TITLE
Add tests for xrd parser

### PR DESCRIPTION
**Pull request by hampusnasstrom**

### CODE REVIEW

**Review by Pepe-Marquez — CHANGES_REQUESTED** [review]
We shall include also in the tests some checks for the normalization to the results section.

**Comment by ka-sarthak** [comment]
I have added a check for normalization to the results section. 
Also added a setup function which uses parse function to generate an archive. This can be used by the test functions like `test_normalize_all`. After the test is completed, the setup function cleans up by deleting the archives.

**Comment by Pepe-Marquez** [comment]
@ka-sarthak, sorry if I wasn't clear enough. I meant that the tests should check if the normalization happens ok to the nomad [results sections](https://nomad-lab.eu/prod/v1/develop/gui/analyze/metainfo/nomad.datamodel.datamodel.EntryArchive/results/method/measurement/xrd), not to the subsection within data (which is great that you wrote the tests). Does this make sense? We can have a chat about it if you want.

**Comment by ka-sarthak** [comment]
@Pepe-Marquez I have added a test for the entryarchive.results section. The only quantity available here is `results.method.measurement.xrd.diffraction_method_name` which is filled through EnumEditQuantity. During the test when the quantity is not filled, this should be defaulted to None.

**Comment by Pepe-Marquez** [comment]
At the moment, your test checks if the parsing of the raw file copies something into results. what you need to check if the normalization of the archive file generated for the measurement, copies stuff to results. 

If you run:
`nomad parse tests/data/m54313_om2th_10.xrdml --show-archive`

This will generate an `../.archive.json` archive for the measurement in the folder, which has the normalization to results and the one you want to check in your tests. 

So after running the first command, you can run the `nomad_parse` again in the newly generated file to see what I mean:

`nomad parse tests/data/m54313_om2th_10.archive.json --show-archive`

I can pass by and tell you what I mean.

**Comment by Pepe-Marquez** [comment]
> At the moment, your test checks if the parsing of the raw file copies something into results. what you need to check if the normalization of the archive file generated for the measurement, copies stuff to results.
> 
> If you run: `nomad parse tests/data/m54313_om2th_10.xrdml --show-archive`
> 
> This will generate an `../.archive.json` archive for the measurement in the folder, which has the normalization to results and the one you want to check in your tests.
> 
> So after running the first command, you can run the `nomad_parse` again in the newly generated file to see what I mean:
> 
> `nomad parse tests/data/m54313_om2th_10.archive.json --show-archive`
> 
> I can pass by and tell you what I mean.

Sorry, my bad. You are checking the right archive, but you should check if you are filling something in [this section](https://nomad-lab.eu/prod/v1/staging/gui/analyze/metainfo/nomad.datamodel.datamodel.EntryArchive/results/properties/structural/diffraction_pattern).

**Comment by ka-sarthak** [comment]
Got it. I have modified the test to access `results.properties.structural.diffraction_pattern[0].incident_beam_wavelength` which is filled by the xrd data. Please review @Pepe-Marquez

**Review by Pepe-Marquez — APPROVED** [review]

**Pull request merged**
